# Generated by rust2rpm 27
%bcond check 1

%global crate resvg

Name:           rust-resvg
Version:        0.22.0
Release:        1%{?dist}
Summary:        SVG rendering library

License:        MPL-2.0
URL:            https://crates.io/crates/resvg
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 23
BuildRequires:  (crate(gif/default) >= 0.11.0 with crate(gif/default) < 0.12.0~)
BuildRequires:  (crate(jpeg-decoder) >= 0.2.0 with crate(jpeg-decoder) < 0.3.0~)
BuildRequires:  (crate(jpeg-decoder/platform_independent) >= 0.2.0 with crate(jpeg-decoder/platform_independent) < 0.3.0~)
BuildRequires:  (crate(log/default) >= 0.4.0 with crate(log/default) < 0.5.0~)
BuildRequires:  (crate(pico-args/default) >= 0.4.0 with crate(pico-args/default) < 0.5.0~)
BuildRequires:  (crate(png/default) >= 0.17.0 with crate(png/default) < 0.18.0~)
BuildRequires:  (crate(rgb/default) >= 0.8.0 with crate(rgb/default) < 0.9.0~)
BuildRequires:  (crate(svgfilters/default) >= 0.4.0 with crate(svgfilters/default) < 0.5.0~)
BuildRequires:  (crate(svgtypes/default) >= 0.8.0 with crate(svgtypes/default) < 0.9.0~)
BuildRequires:  (crate(tiny-skia/default) >= 0.6.1 with crate(tiny-skia/default) < 0.7.0~)
BuildRequires:  (crate(usvg) >= 0.22.0 with crate(usvg) < 0.23.0~)
BuildRequires:  (crate(usvg/filter) >= 0.22.0 with crate(usvg/filter) < 0.23.0~)
BuildRequires:  (crate(usvg/memmap-fonts) >= 0.22.0 with crate(usvg/memmap-fonts) < 0.23.0~)
BuildRequires:  (crate(usvg/system-fonts) >= 0.22.0 with crate(usvg/system-fonts) < 0.23.0~)
BuildRequires:  (crate(usvg/text) >= 0.22.0 with crate(usvg/text) < 0.23.0~)
%if %{with check}
BuildRequires:  (crate(once_cell/default) >= 1.5.0 with crate(once_cell/default) < 2.0.0~)
%endif

%global _description %{expand:
An SVG rendering library.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
License:        Apache-2.0 AND MIT

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE.txt
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md
%doc version-bump.md
%{_bindir}/resvg

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(resvg) = 0.22.0
Requires:       (crate(gif/default) >= 0.11.0 with crate(gif/default) < 0.12.0~)
Requires:       (crate(jpeg-decoder) >= 0.2.0 with crate(jpeg-decoder) < 0.3.0~)
Requires:       (crate(jpeg-decoder/platform_independent) >= 0.2.0 with crate(jpeg-decoder/platform_independent) < 0.3.0~)
Requires:       (crate(log/default) >= 0.4.0 with crate(log/default) < 0.5.0~)
Requires:       (crate(pico-args/default) >= 0.4.0 with crate(pico-args/default) < 0.5.0~)
Requires:       (crate(png/default) >= 0.17.0 with crate(png/default) < 0.18.0~)
Requires:       (crate(rgb/default) >= 0.8.0 with crate(rgb/default) < 0.9.0~)
Requires:       (crate(svgtypes/default) >= 0.8.0 with crate(svgtypes/default) < 0.9.0~)
Requires:       (crate(tiny-skia/default) >= 0.6.1 with crate(tiny-skia/default) < 0.7.0~)
Requires:       (crate(usvg) >= 0.22.0 with crate(usvg) < 0.23.0~)
Requires:       cargo

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.txt
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/version-bump.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(resvg/default) = 0.22.0
Requires:       cargo
Requires:       crate(resvg) = 0.22.0
Requires:       crate(resvg/filter) = 0.22.0
Requires:       crate(resvg/memmap-fonts) = 0.22.0
Requires:       crate(resvg/system-fonts) = 0.22.0
Requires:       crate(resvg/text) = 0.22.0

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dump-svg-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(resvg/dump-svg) = 0.22.0
Requires:       (crate(usvg/export) >= 0.22.0 with crate(usvg/export) < 0.23.0~)
Requires:       cargo
Requires:       crate(resvg) = 0.22.0

%description -n %{name}+dump-svg-devel %{_description}

This package contains library source intended for building other packages which
use the "dump-svg" feature of the "%{crate}" crate.

%files       -n %{name}+dump-svg-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+filter-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(resvg/filter) = 0.22.0
Requires:       (crate(usvg/filter) >= 0.22.0 with crate(usvg/filter) < 0.23.0~)
Requires:       cargo
Requires:       crate(resvg) = 0.22.0
Requires:       crate(resvg/svgfilters) = 0.22.0

%description -n %{name}+filter-devel %{_description}

This package contains library source intended for building other packages which
use the "filter" feature of the "%{crate}" crate.

%files       -n %{name}+filter-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+memmap-fonts-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(resvg/memmap-fonts) = 0.22.0
Requires:       (crate(usvg/memmap-fonts) >= 0.22.0 with crate(usvg/memmap-fonts) < 0.23.0~)
Requires:       cargo
Requires:       crate(resvg) = 0.22.0

%description -n %{name}+memmap-fonts-devel %{_description}

This package contains library source intended for building other packages which
use the "memmap-fonts" feature of the "%{crate}" crate.

%files       -n %{name}+memmap-fonts-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+svgfilters-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(resvg/svgfilters) = 0.22.0
Requires:       (crate(svgfilters/default) >= 0.4.0 with crate(svgfilters/default) < 0.5.0~)
Requires:       cargo
Requires:       crate(resvg) = 0.22.0

%description -n %{name}+svgfilters-devel %{_description}

This package contains library source intended for building other packages which
use the "svgfilters" feature of the "%{crate}" crate.

%files       -n %{name}+svgfilters-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+system-fonts-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(resvg/system-fonts) = 0.22.0
Requires:       (crate(usvg/system-fonts) >= 0.22.0 with crate(usvg/system-fonts) < 0.23.0~)
Requires:       cargo
Requires:       crate(resvg) = 0.22.0

%description -n %{name}+system-fonts-devel %{_description}

This package contains library source intended for building other packages which
use the "system-fonts" feature of the "%{crate}" crate.

%files       -n %{name}+system-fonts-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+text-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(resvg/text) = 0.22.0
Requires:       (crate(usvg/text) >= 0.22.0 with crate(usvg/text) < 0.23.0~)
Requires:       cargo
Requires:       crate(resvg) = 0.22.0

%description -n %{name}+text-devel %{_description}

This package contains library source intended for building other packages which
use the "text" feature of the "%{crate}" crate.

%files       -n %{name}+text-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Jun 03 2025 ImperatorStorm <imperatorstorm11@protonmail.com> - 0.22.0-1
- Initial package
