name: Font CI - noto-color-emoji-fox

on:
  schedule:
  - cron: '0 0 * * 0'
  push:
    paths:
        - ".github/workflows/fontbuild noto-color-emoji-fox.yml"
        - "noto-color-emoji-fox/*"
  pull_request:
    paths:
        - ".github/workflows/fontbuild noto-color-emoji-fox.yml"
        - "noto-color-emoji-fox/*"
  workflow_dispatch:

jobs:
  fontbuild:
    runs-on: ubuntu-latest
    container: fedora:rawhide
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Font RPM
      run: |
        dnf distro-sync --assumeyes
        dnf install mock --assumeyes
        cd noto-color-emoji-fox
        mock -r fedora-rawhide-x86_64 --buildsrpm --spec google-noto-emoji-fonts.spec
        cd /var/lib/mock/fedora-rawhide-x86_64/result/
        mock -r fedora-rawhide-x86_64 google-noto-emoji-fonts.src.rpm
    - name: Upload Font
      uses: actions/upload-artifact@v3
      with:
          name: font
          path: |
            /var/lib/mock/fedora-rawhide-x86_64/result/*.rpm
            !/var/lib/mock/fedora-rawhide-x86_64/result/*.src.rpm
    - name: Upload logs on failure
      uses: actions/upload-artifact@v3
      if: failure()
      with:
          name: logs
          path: |
            /var/lib/mock/fedora-rawhide-x86_64/result/*
            !/var/lib/mock/fedora-rawhide-x86_64/result/*.src.rpm
