name: Font CI - noto-color-emoji-fox

on:
  push:
    paths:
        - ".github/workflows/fontbuild noto-color-emoji-fox.yml"
        - "noto-color-emoji-fox/*"
  pull_request:
    paths:
        - ".github/workflows/fontbuild noto-color-emoji-fox.yml"
        - "noto-color-emoji-fox/*"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Font
      run: |
        pacman -Syu --noconfirm
        pacman -S base-devel python-pip scour inkscape git imagemagick pngquant cairo zopfli noto-fonts --needed --noconfirm
        cd noto-color-emoji-fox
        mv -v scour_svg.sh.new ..
        git clone --depth=1 https://github.com/googlefonts/noto-emoji .
        mv -v ../scour_svg.sh.new .
        curl https://raw.githubusercontent.com/googlefonts/noto-emoji/5628587386c78161f87aa2ca9ddee37c2e8ea212/svg/emoji_u1f98a.svg -o svg/emoji_u1f98a.svg
        SRC_DIR="$(pwd)/svg" DST_DIR="$(pwd)/scoured/svg" ./scour_svg.sh.new
        mv -v scoured/svg/* svg/
        inkscape -o png/32/emoji_u1f98a.png -w 32 -h 32 svg/emoji_u1f98a.svg
        inkscape -o png/72/emoji_u1f98a.png -w 72 -h 72 svg/emoji_u1f98a.svg
        inkscape -o png/128/emoji_u1f98a.png -w 128 -h 128 svg/emoji_u1f98a.svg
        inkscape -o png/512/emoji_u1f98a.png -w 512 -h 512 svg/emoji_u1f98a.svg
        rm --verbose fonts/*
        python -m venv emojibuild
        source emojibuild/bin/activate
        pip install -r requirements.txt --verbose
        make -j$(nproc) --no-silent
        tar --zstd --verbose -cf font.tar.zst NotoColorEmoji.ttf
        mv -v font.tar.zst ..
    - name: Upload Font
      uses: actions/upload-artifact@v3
      with:
          name: font
          path: |
            font.tar.zst