name: Font CI - noto-color-emoji-fox

on:
  push:
    paths:
        - ".github/workflows/fontbuild_noto-color-emoji-fox.yml"
        - "noto-color-emoji-fox/*"
  pull_request:
    paths:
        - ".github/workflows/fontbuild_noto-color-emoji-fox.yml"
        - "noto-color-emoji-fox/*"
  workflow_dispatch:

jobs:
  fontbuild:
    runs-on: ubuntu-latest
    container: fedora:rawhide
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Font RPM
      run: |
        dnf distro-sync --assumeyes
        dnf install rpm-build gcc fontpackages-devel fonttools python3-fonttools nototools python3-nototools python3-devel GraphicsMagick pngquant zopfli cairo-devel make curl which rpmdevtools git-all --assumeyes
        cd noto-color-emoji-fox
        rpmdev-setuptree
        spectool -gR google-noto-emoji-fonts.spec
        cp ./*.patch $(rpm --eval=%{_sourcedir})
        rpmbuild -bb google-noto-emoji-fonts.spec
    - name: Upload Font
      uses: actions/upload-artifact@v4
      with:
          name: font
          path: |
            /github/home/rpmbuild/RPMS/*
