name: Font CI - noto-color-emoji-fox

on:
  schedule:
  - cron: '0 0 * * 0'
  push:
    paths:
        - ".github/workflows/fontbuild noto-color-emoji-fox.yml"
        - "noto-color-emoji-fox/*"
  pull_request:
    paths:
        - ".github/workflows/fontbuild noto-color-emoji-fox.yml"
        - "noto-color-emoji-fox/*"
  workflow_dispatch:

jobs:
  fontbuild:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Font
      run: |
        pacman -Syu --noconfirm
        pacman -S base-devel python-pip inkscape git imagemagick pngquant cairo zopfli noto-fonts findutils --needed --noconfirm
        cd noto-color-emoji-fox
        rm .gitkeep
        git clone --depth=1 https://github.com/googlefonts/noto-emoji .
        curl https://raw.githubusercontent.com/googlefonts/noto-emoji/5628587386c78161f87aa2ca9ddee37c2e8ea212/svg/emoji_u1f98a.svg -o svg/emoji_u1f98a.svg
        inkscape -o png/32/emoji_u1f98a.png -w 32 -h 32 svg/emoji_u1f98a.svg
        inkscape -o png/72/emoji_u1f98a.png -w 72 -h 72 svg/emoji_u1f98a.svg
        inkscape -o png/128/emoji_u1f98a.png -w 128 -h 128 svg/emoji_u1f98a.svg
        inkscape -o png/512/emoji_u1f98a.png -w 512 -h 512 svg/emoji_u1f98a.svg
        rm --verbose fonts/*
        python -m venv emojibuild
        source emojibuild/bin/activate
        pip install -r requirements.txt --verbose
        make -j$(nproc)
        mv *.ttf fonts/
        cd colrv1
        cp ../colrv1_generate_configs.py .
        nanoemoji all.toml
        cp colrv1/build/NotoColorEmoji.ttf fonts/Noto-COLRv1.ttf
        cd ..
        python colrv1_postproc.py
        tar --zstd --verbose -cf font.tar.zst fonts/NotoColorEmoji.ttf
    - name: Upload Font
      uses: actions/upload-artifact@v3
      with:
          name: font
          path: |
            font.tar.zst