name: Font CI - noto-color-emoji-fox

on:
  schedule:
  - cron: '0 0 * * 0'
  push:
    paths:
        - ".github/workflows/fontbuild noto-color-emoji-fox.yml"
        - "noto-color-emoji-fox/*"
  pull_request:
    paths:
        - ".github/workflows/fontbuild noto-color-emoji-fox.yml"
        - "noto-color-emoji-fox/*"
  workflow_dispatch:

jobs:
  fontbuild:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Prepare
      run: |
        cd noto-color-emoji-fox
        rm .gitkeep
        cd ../
    - name: Checkout Font
      uses: actions/checkout@v3
      with:
        repository: googlefonts/noto-emoji
        path: noto-color-emoji-fox
    - name: Build Font
      run: |
        set -x
        pacman -Syu --noconfirm
        pacman -S base-devel python-pip inkscape git imagemagick pngquant cairo zopfli noto-fonts findutils zstd --needed --noconfirm
        curl https://raw.githubusercontent.com/googlefonts/noto-emoji/5628587386c78161f87aa2ca9ddee37c2e8ea212/svg/emoji_u1f98a.svg -o svg/emoji_u1f98a.svg
        inkscape -o png/32/emoji_u1f98a.png -w 32 -h 32 svg/emoji_u1f98a.svg
        inkscape -o png/72/emoji_u1f98a.png -w 72 -h 72 svg/emoji_u1f98a.svg
        inkscape -o png/128/emoji_u1f98a.png -w 128 -h 128 svg/emoji_u1f98a.svg
        inkscape -o png/512/emoji_u1f98a.png -w 512 -h 512 svg/emoji_u1f98a.svg
        rm --verbose fonts/*
        python -m venv emojibuild
        source emojibuild/bin/activate
        pip install -r requirements.txt --verbose
        python size_check.py
        make -j$(nproc) VERBOSE=1
        mv *.ttf fonts/
        cd colrv1
        nanoemoji all.toml
        cp build/NotoColorEmoji.ttf ../fonts/Noto-COLRv1.ttf
        cp build/NotoColorEmoji.ttf ../fonts/Noto-COLRv1-noflags.ttf
        cd ..
        python colrv1_postproc.py
        tar --verbose -cf font.tar fonts/*.ttf
        zstd -15 -T0 font.tar font.tar.zst
    - name: Upload Font
      uses: actions/upload-artifact@v3
      with:
          name: font
          path: |
            noto-color-emoji-fox/font.tar.zst
