name: Font CI - noto-color-emoji-fox

on:
  push:
    paths:
        - ".github/workflows/fontbuild_noto-color-emoji-fox.yml"
        - "noto-color-emoji-fox/*"
  pull_request:
    paths:
        - ".github/workflows/fontbuild_noto-color-emoji-fox.yml"
        - "noto-color-emoji-fox/*"
  workflow_dispatch:

jobs:
  fontbuild:
    runs-on: ubuntu-latest
    container: fedora:rawhide
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Font RPM
      run: |
        dnf5 distro-sync --assumeyes
        dnf5 install rpm-build gcc fontpackages-devel fonttools python3-fonttools nototools python3-nototools python3-devel GraphicsMagick pngquant zopfli cairo-devel make curl which rpmdevtools git-all python-absl-py python-lxml ninja-build --assumeyes
        rpmdev-setuptree
        cd resvg
        spectool -gR rust-resvg.spec
        rpmbuild -bb rust-resvg.spec
        dnf5 install /github/home/rpmbuild/RPMS/*
        cd ../nanoemoji
        spectool -gR nanoemoji.spec
        rpmbuild -bb nanoemoji.spec
        dnf5 install /github/home/rpmbuild/RPMS/*
        cd ../noto-color-emoji-fox
        spectool -gR google-noto-emoji-fonts.spec
        cp ./*.patch ./*.png $(rpm --eval=%{_sourcedir})
        rpmbuild -bb google-noto-emoji-fonts.spec
    - name: Upload Font
      uses: actions/upload-artifact@v4
      with:
          name: RPMs
          path: |
            /github/home/rpmbuild/RPMS/*
