name: Makepkg CI - noto-color-emoji-fox

env:
  GPG_TTY: $(tty)

on:
  push:
    paths:
        - "noto-color-emoji-fox/**"
        - "makepkg.conf"
        - ".github/workflows/makepkg_noto-color-emoji-fox.yml"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Makepkg
      run: |
        pacman -Syu --noconfirm namcap git rust
        useradd builder -m
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        BASEDIR="$PWD"
        git clone https://aur.archlinux.org/paru.git
        chmod -R a+rw .
        cd paru
        sudo -u builder echo -n "${{ secrets.GPG_PRIVATE_KEY }}" | sudo -u builder base64 --decode | sudo -u builder gpg --import --batch --no-tty
        sudo -u builder makepkg -si
        cd ..
        sudo -u builder paru -S nanoemoji python-nototools --noconfirm --mflags --config=../makepkg.conf
        cd noto-color-emoji-fox
        sudo -u builder makepkg -s --sign --noconfirm --config=../makepkg.conf
    - name: Namcap
      run: cd noto-color-emoji-fox && namcap *.pkg.tar.zst
    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
          name: packages
          path: |
            noto-color-emoji-fox/*.zst
            noto-color-emoji-fox/*.zst.sig
