name: Makepkg CI - 3beans-git

env:
  GPG_TTY: $(tty)
  SCCACHE_GHA_ENABLED: on

on:
  push:
    paths:
        - "3beans-git/**"
        - "makepkg.conf"
        - ".github/workflows/makepkg_3beans-git.yml"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.10
    - name: Add sccache compiler symlinks
      run: |
        ./.ci/sccache-setup.sh
    - name: Makepkg
      run: |
        pacman -Syu --noconfirm --needed namcap git
        git clone https://aur.archlinux.org/wxgtk-git.git
        useradd builder -m
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chmod -R a+rw .
        chown -R builder:root /home/builder
        BASEDIR="$PWD"
        cd wxgtk-git
        sudo -u builder echo -n "${{ secrets.GPG_PRIVATE_KEY }}" | sudo -u builder base64 --decode | sudo -u builder gpg --import --batch --no-tty
        sudo -u builder makepkg -si --sign --noconfirm --config=../makepkg.conf
        cd ../3beans-git
        sudo -u builder makepkg -s --sign --noconfirm --config=../makepkg.conf
    - name: Namcap
      run: cd 3beans-git && namcap *.pkg.tar.zst
    - name: Upload Packages
      uses: actions/upload-artifact@v7
      with:
          name: packages
          compression-level: 0
          path: |
            wxgtk-git/*.zst
            wxgtk-git/*.zst.sig
            3beans-git/*.zst
            3beans-git/*.zst.sig
    #        ${{ steps.makepkg.outputs.pkgfile0 }}.sig