name: Makepkg CI - aseprite

env:
  GPG_TTY: $(tty)

on:
  push:
    paths:
        - "aseprite/**"
        - "makepkg.conf"
        - ".github/workflows/makepkg aseprite.yml"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Makepkg
      run: |
        echo ${{ github.event.name }}
        pacman -Syu --noconfirm namcap
        useradd builder -m
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chmod -R a+rw .
        BASEDIR="$PWD"
        cd aseprite
        sudo -u builder echo -n "${{ secrets.GPG_PRIVATE_KEY }}" | sudo -u builder base64 --decode | sudo -u builder gpg --import --batch --no-tty
        sudo -u builder gpg --locate-keys torvalds@kernel.org gregkh@kernel.org
        sudo -u builder makepkg -s --sign --noconfirm --config=../makepkg.conf
    - name: Namcap
      run: namcap *.pkg.tar.zst
    - name: Upload Packages
      uses: actions/upload-artifact@v3
      with:
          name: packages
          path: |
            aseprite/*.zst
            aseprite/*.zst.sig
            !aseprite/*debug*.zst
            !aseprite/*debug*.zst.sig
    #        ${{ steps.makepkg.outputs.pkgfile0 }}.sig
    - uses: actions/upload-artifact@v3
      with:
          name: debug_packages
          path: |
            aseprite/*debug*.zst
            aseprite/*debug*.zst.sig