name: Makepkg CI

on: 
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
  workflow_dispatch:
jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
    - name: Print & Upload Package Files
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.makepkg.outputs.pkgfile0 }}
        path: ${{ steps.makepkg.outputs.pkgfile0 }}