name: Makepkg CI - repak

env:
  GPG_TTY: $(tty)

on:
  push:
    paths:
        - "repak/**"
        - "makepkg.conf"
        - ".github/workflows/makepkg_repak.yml"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Cache sccache output
      uses: actions/cache@v5
      with:
        path: |
          /github/home/.cache/sccache
        key: ${{ hashFiles('**/makepkg.conf') }}
    - name: Add Sccache wrappers to PATH
      run: |
        ./.ci/sccache-setup.sh
        echo "/usr/lib/sccache/bin" >> $GITHUB_PATH
    - name: Makepkg
      run: |
        echo ${{ github.event.name }}
        pacman -Syu --noconfirm namcap sccache which
        useradd builder -m
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chmod -R a+rw .
        BASEDIR="$PWD"
        cd repak
        sudo -u builder ls /usr/lib/sccache/bin/
        sudo -u builder echo $PATH
        sudo -u builder which gcc
        sudo -u builder echo -n "${{ secrets.GPG_PRIVATE_KEY }}" | sudo -u builder base64 --decode | sudo -u builder gpg --import --batch --no-tty
        sudo -u builder makepkg -s --sign --noconfirm --config=../makepkg.conf
        sudo -u builder du -hs $HOME/.cache/sccache
    - name: Namcap
      run: cd repak && namcap *.pkg.tar.zst
    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
          name: packages
          path: |
            repak/*.zst
            repak/*.zst.sig
            !repak/*debug*.zst
            !repak/*debug*.zst.sig
    #        ${{ steps.makepkg.outputs.pkgfile0 }}.sig