name: Makepkg CI - Aseprite
on:
  push:
    paths:
        - "aseprite/**"
  pull_request:
    paths:
        - "aseprite/**"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
          pkgdir: "aseprite"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
          path: ${{ steps.makepkg.outputs.pkgfile0 }}