name: Makepkg CI - Minizip-git
on:
  push:
    paths:
        - "minizip-git/**"
  pull_request:
    paths:
        - "minizip-git/**"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
          pkgdir: "minizip-git"
          makepkgArgs: "--skippgpcheck --config=../makepkg.conf"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
          path: ${{ steps.makepkg.outputs.pkgfile0 }}