name: Makepkg CI - Minizip-git
on:
  push:
    paths:
        - "minizip-git/**"
  pull_request:
    paths:
        - "minizip-git/**"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v1
      env:
         GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
         PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: Makepkg Build
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
          pkgdir: "minizip-git"
          makepkgArgs: "--skippgpcheck --sign --config=../makepkg.conf"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
          path: ${{ steps.makepkg.outputs.pkgfile0 }} ${{ steps.makepkg.outputs.pkgfile1 }}