name: Makepkg CI - quilt-server

env:
  GPG_TTY: $(tty)

on:
  push:
    paths:
        - "quilt-server/**"
        - "makepkg.conf"
        - ".github/workflows/makepkg quilt-server.yml"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg
      run: |
        pacman -Syu --noconfirm
        useradd builder -m
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chmod -R a+rw .
        BASEDIR="$PWD"
        cd quilt-server
        sudo -u builder echo -n "${{ secrets.GPG_PRIVATE_KEY }}" | sudo -u builder base64 --decode | sudo -u builder gpg --import --batch --no-tty
        sudo -u builder gpg --locate-keys torvalds@kernel.org gregkh@kernel.org
        sudo -u builder makepkg -s --sign --noconfirm --config=../makepkg.conf
    - name: Upload Packages
      uses: actions/upload-artifact@v2
      with:
          name: packages
          path: |
            quilt-server/*.zst
            quilt-server/*.zst.sig
            !quilt-server/*debug*.zst
            !quilt-server/*debug*.zst.sig
    #        ${{ steps.makepkg.outputs.pkgfile0 }}.sig