name: Makepkg CI - minizip-git

env:
  GPG_TTY: $(tty)

on:
  pull_request:
    paths:
        - "minizip-git/**"
        - "makepkg.conf"
        - ".github/workflows/prbuild minizip-git.yml"
  workflow_dispatch:

jobs:
  prbuild:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg
      run: |
        pacman -Syu --noconfirm
        useradd builder -m
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chmod -R a+rw .
        BASEDIR="$PWD"
        cd minizip-git
        sudo -u builder makepkg -s --noconfirm --skippgpcheck --config=../makepkg.conf
    - name: Upload Packages
      uses: actions/upload-artifact@v2
      with:
          name: packages
          path: |
            minizip-git/*.zst
            !minizip-git/*debug*.zst
    - uses: actions/upload-artifact@v2
      with:
          name: debug_packages
          path: |
            minizip-git/*debug*.zst