name: PRbuild CI - aseprite

env:
  GPG_TTY: $(tty)

on:
  pull_request:
    paths:
        - "aseprite/**"
        - "makepkg.conf"
        - ".github/workflows/prbuild aseprite.yml"
  workflow_dispatch:

jobs:
  prbuild:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Makepkg
      run: |
        pacman -Syu --noconfirm namcap
        useradd builder -m
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chmod -R a+rw .
        BASEDIR="$PWD"
        cd aseprite
        sudo -u builder makepkg -s --noconfirm --skippgpcheck --config=../makepkg.conf
    - name: Namcap
      run: cd aseprite && namcap *.pkg.tar.zst